cart/urls.py
from django.urls import path
from .views import cart_view, add_to_cart, remove_from_cart, checkout_view

app_name = 'cart'

urlpatterns = [
    path('cart/', cart_view, name='cart_view'),
    path('add-to-cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:item_id>/', remove_from_cart, name='remove_from_cart'),
    path('checkout/', checkout_view, name='checkout'),
]

marketplace/marketplace/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from products.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include('users.urls')),
    path('products', include('products.urls')),
    path('', home, name='home'),
    path('cart/', include('cart.urls', namespace='cart')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path
from .views import custom_password_change_view, profile_view, edit_profile, register_view, login_view, logout_view, \
    send_confirmation_email

app_name = 'users'

urlpatterns = [
    path('register/',
         register_view, name='register'),
    path('login/',
         login_view, name='login'),
    path('logout/',
         logout_view, name='logout'),

    path('password-change/',
         custom_password_change_view,name='password_change'),
    path('password-change/done/',
         PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),name='password_change_done'),

    path('profile/', profile_view, name='profile'),
    path('profile/edit/', edit_profile, name='edit_profile'),

    path('send-email/', send_confirmation_email, name='send_confirmation'),
]

users/models.py
from time import timezone

from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    ROLE_CHOICES = (
        ('buyer', 'Покупатель'),
        ('seller', 'Продавец'),
    )
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='buyer')
    photo = models.ImageField(upload_to='user_photos/', blank=True, null=True)
    date_of_birth = models.DateField(null=True, blank=True)
    email_confirmed = models.BooleanField(default=False)
    @property
    def is_buyer(self):
        return self.role == 'buyer'

    @property
    def is_seller(self):
        return self.role == 'seller'

    def send_confirmation_email(self):
        from django.core.mail import send_mail
        from django.conf import settings
        from django.contrib.auth.tokens import default_token_generator
        from django.utils.http import urlsafe_base64_encode
        from django.utils.encoding import force_bytes

        token = default_token_generator.make_token(self)
        uid = urlsafe_base64_encode(force_bytes(self.pk))
        confirmation_link = f"{settings.DOMAIN}/confirm-email/{uid}/{token}/"

        send_mail(
            'Подтверждение email',
            f'Для подтверждения email перейдите по ссылке: {confirmation_link}',
            settings.DEFAULT_FROM_EMAIL,
            [self.email],
            fail_silently=False,
        )
        self.confirmation_sent_date = timezone.now()
        self.save()

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser

class RegisterForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2', 'role', 'photo', 'date_of_birth']

class LoginForm(AuthenticationForm):
    pass



User = get_user_model()

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'photo', 'date_of_birth']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'date_of_birth': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),

        }

users/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, update_session_auth_hash
from django.urls import reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.contrib import messages

from marketplace.settings import DOMAIN
from products.models import Product
from .forms import RegisterForm, LoginForm, ProfileEditForm
from .models import CustomUser


# регистрация \ логин \ выход
def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = RegisterForm()
    return render(request, 'registration/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('home')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('login')
# конец




# смена пароля
@login_required
def custom_password_change_view(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # чтобы не выкинуло из аккаунта
            return redirect('password_change_done')
    else:
        form = PasswordChangeForm(user=request.user)

    return render(request, 'registration/password_change.html', {'form': form})

# конец



@login_required
def profile_view(request):
    user = request.user
    products = Product.objects.filter(seller=user)
    return render(request, 'users/profile.html', {'products': products})




@login_required
def edit_profile(request):
    user = request.user
    if request.method == 'POST':
        form = ProfileEditForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = ProfileEditForm(instance=user)

    return render(request, 'users/edit_profile.html', {'form': form})




@login_required
def send_confirmation_email(request):
    user = request.user
    try:
        subject = 'Приветствие и подтверждение'
        message = f'Здравствуйте, {user.username}!\n\nСпасибо за регистрацию!'

        send_mail(
            subject,
            message,
            settings.DEFAULT_FROM_EMAIL,
            [user.email],
            fail_silently=False,
        )
        messages.success(request, 'Приветственное письмо отправлено на вашу почту.')
    except Exception as e:
        messages.error(request, f'Ошибка отправки письма: {str(e)}')
    return redirect('/users/profile/')

templates/users/edit_profil.html
{% extends 'base.html' %}

{% block title %}Редактирование профиля{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Редактировать профиль</h1>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{% url 'profile' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

templates/users/edit_profile.html
{% extends 'base.html' %}

{% block title %}Редактирование профиля{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Редактировать профиль</h1>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
    <a href="{% url 'users:password_change' %}" class="btn btn-outline-primary">
    <i class="bi bi-key"></i> Сменить пароль
    </a>
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{% url 'users:profile' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Профиль пользователя{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Профиль: {{ user.username }}</h1>
    <div class="col-md-4 text-center">
      {% if user.photo %}
        <img src="{{ user.photo.url }}" class="img-thumbnail mb-3" style="max-height: 200px;">
      {% else %}
        <img src="{% static 'images/default-user.png' %}" class="img-thumbnail mb-3" style="max-height: 200px;">
      {% endif %}
    </div>
    <div class="card p-4">
        <h4>Личная информация</h4>
        <p><strong>Имя пользователя:</strong> {{ user.username }}</p>

            <div class="mb-3">
        <p class="mb-1"><strong>Email:</strong> {{ user.email }}</p>
        {% if not user.email_confirmed %}
            <div class="alert alert-warning p-2 d-flex align-items-center">
                <i class="bi bi-exclamation-triangle-fill me-2"></i>
                <span>Почта не подтверждена</span>
                <form method="post" action="{% url 'users:send_confirmation' %}" class="ms-2">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-warning">
                        <i class="bi bi-envelope-plus"></i> Отправить подтверждение
                    </button>
                </form>
            </div>
        {% else %}
            <div class="alert alert-success p-2">
                <i class="bi bi-check-circle-fill me-2"></i>
                Email подтверждён
            </div>
        {% endif %}
    </div>

        <p><strong>Роль:</strong>
            {% if user.is_seller %}
                Продавец
            {% else %}
                Покупатель
            {% endif %}
        </p>

        <div class="d-flex gap-2">
            <a href="{% url 'users:logout' %}">Выйти</a>
            <a href="{% url 'users:edit_profile' %}" class="btn btn-secondary">Редактировать профиль</a>
            <a href="{% url 'users:password_change' %}" class="btn btn-primary">Сменить пароль</a>
        </div>
    </div>

    {% if user.is_seller %}
        <div class="mt-5">
            <h3>Ваши товары</h3>
            {% if products %}
                <ul class="list-group">
                    {% for product in products %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{% url 'product_detail' product.pk %}">{{ product.name }}</a>
                            <span>{{ product.price }} $</span>
                            <a href="{% url 'edit_product' product.pk %}">Редактировать</a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>Вы пока не добавили ни одного товара.</p>
            {% endif %}
        </div>
    {% endif %}
</div>
{% endblock %}